//import React from 'react';

const picarr = [
    "https://static.toiimg.com/photo/81605081.cms",
    "https://upload.wikimedia.org/wikipedia/commons/4/47/New_york_times_square-terabass.jpg",
    "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/4b/5d/10/caption.jpg?w=500&h=300&s=1&cx=1005&cy=690&chk=v1_2ed86f729380ea073850",
    "https://www.planetware.com/photos-large/AUS/australia-brisbane-city-2.jpg",
    "https://pix10.agoda.net/hotelImages/6551658/0/f213aa4557c0fc770d972a2495995527.jpg?s=1024x768",
    "https://media.cntraveler.com/photos/5a903dd660543c4ae96c2e74/16:9/w_2560%2Cc_limit/GettyImages-497268617.jpg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_CvmtDVBB86HSLNFyq9pnpYXk6hdiLnnpeA&usqp=CAU",
    "https://www.oyorooms.com/travel-guide/wp-content/uploads/2019/11/shutterstock_1350638618.jpg",
    "https://resize.indiatvnews.com/en/resize/newbucket/1200_-/2020/12/pti28-12-2020-000048b-1609160104.jpg",
    "https://res.cloudinary.com/dwzmsvp7f/image/fetch/q_75,f_auto,w_1316/https%3A%2F%2Fmedia.insider.in%2Fimage%2Fupload%2Fc_crop%2Cg_custom%2Fv1581685165%2Fs4ttjwmxzht5gemp4c4x.jpg",
    "https://images.unsplash.com/photo-1569383746724-6f1b882b8f46?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fG1vcm9jY298ZW58MHx8MHx8&ixlib=rb-1.2.1&w=1000&q=80",
    "https://media.istockphoto.com/photos/autumn-morning-at-the-cathedral-picture-id621235832?k=20&m=621235832&s=612x612&w=0&h=M072MpUXno496zSC7RmDv1Qy_JnFZ3pdFVw7zayYOEw=",
    "https://udg-about-puma-prod-endpoint.azureedge.net/-/media/images/careers/locations/latam---chile/m-18_chilesantiago.jpg?as=1&h=300&iar=1&w=400&rev=c68cedcaffa64f1cb2b4171ef0af39dc&hash=ADF924F20140BB47D718E6DD64A7C796",

]
const data = [
    {
        dp: picarr[0],
        title: "Experience Paris like a European for 3 Days",
        price: "Rs 80000",
        description:" Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        action: "Not Interested",
        visible:"true",
    },
    {
        dp: picarr[1],
        title: "Visit Newyork for 3 Days",
        price: "Rs 100000",
        description:" Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        action: "Not Interested",
        visible:"true",
    },
    {
        dp: picarr[2],
        title: "Visit Tokyo for 3 Days",
        price: "Rs 60000",
        description:" Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        action: "Not Interested",
        visible:"true",
    },
    {
        dp: picarr[3],
        title: "Visit Brisbane for 3 Days",
        price: "Rs 90000",
        description:" Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        action: "Not Interested",
        visible:"true",
    },
    {
        dp: picarr[4],
        title: "Visit Pataya for 3 Days",
        price: "Rs 40000",
        description:" Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        action: "Not Interested",
        visible:"true",
    },
    {
        dp: picarr[5],
        title: "Visit Rome for 3 Days",
        price: "Rs 70000",
        description:" Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        action: "Not Interested",
        visible:"true",
    },
    {
        dp: picarr[6],
        title: "Visit kolkata for 3 Days",
        price: "Rs 70000",
        description:" Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        action: "Not Interested",
        visible:"true",
    },
    {
        dp: picarr[7],
        title: "Visit Manali for 3 Days",
        price: "Rs 70000",
        description:" Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        action: "Not Interested",
        visible:"true",
    },
    {
        dp: picarr[8],
        title: "Visit Shimla for 3 Days",
        price: "Rs 70000",
        description:" Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        action: "Not Interested",
        visible:"true",
    },
    {
        dp: picarr[9],
        title: "Visit Leh for 3 Days",
        price: "Rs 70000",
        description:" Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        action: "Not Interested",
        visible:"true",
    },
    {
        dp: picarr[10],
        title: "Visit Morocco for 3 Days",
        price: "Rs 70000",
        description:" Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        action: "Not Interested",
        visible:"true",
    },
    {
        dp: picarr[11],
        title: "Visit Moscow for 3 Days",
        price: "Rs 70000",
        description:" Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        action: "Not Interested",
        visible:"true",
    },
    {
        dp: picarr[12],
        title: "Visit chile for 3 Days",
        price: "Rs 70000",
        description:" Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        action: "Not Interested",
        visible:"true",
    },
   
]

export default data;